[workspace]

members = [
    "dynisland",
    "abi",
    "core",
    "dynisland-modules/*",
]
exclude = ["dynisland-modules/dynisland-module-template"]
resolver = "2"

[profile.release]
strip = true
opt-level = "z"
lto = true

# debug = true

[workspace.dependencies]
anyhow = "1.0.86"
gtk = { version = "0.8.0", package = "gtk4", features = ["v4_12"] }
gdk = { version = "0.8.0", package = "gdk4" }
glib = {version="0.19.5"}
glib-macros = { version="0.19.5"}
glib-build-tools = { version="0.19.0" }
tokio = { version = "1.39.0"}
serde = { version = "1.0.188", features = ["serde_derive"] }
log = "0.4.20"
ron = "0.8.1"
linkme = "0.3.17"
abi_stable = "0.11.3"
env_logger = "0.11.2"
gtk-layer-shell= { version = "0.3.0", package = "gtk4-layer-shell"}
grass = {version = "0.13.4", default-features = false, features = ["macro"]} #scss parsing
