[package]
name = "dynisland"
version = "0.1.0"
edition = "2021"
license = "mit"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

dynisland-core = { path = "../dynisland-core" }
dynisland-abi = { path = "../dynisland-abi" }
# dynisland-modules = { path = "../dynisland-modules"}

anyhow = { workspace = true }
gtk = { workspace = true }
gtk-layer-shell = { workspace = true }
gdk = { workspace = true }
glib = { workspace = true }
tokio = { workspace = true, features = ["rt", "time", "sync", "macros"] }
serde = { workspace = true, features = ["serde_derive"] }
log = { workspace = true }
ron = { workspace = true }
linkme = { workspace = true }
abi_stable = { workspace = true }
env_logger = { workspace = true }


notify = { version = "6.1.1", features = ["fsevent-sys"] }
grass = { workspace = true }                               #scss parsing
colored = "2.1.0"

# css-anim = {path = "../../css-anim", version = "*"}
