[package]
name = "dynisland"
version = "0.1.0"
edition = "2021"
license = "mit"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

dynisland-core = { path = "../dynisland-core"}
dynisland-modules = { path = "../dynisland-modules"}
anyhow = "1.0.75"
gtk = "0.18.1"
gdk = "0.18.0"
gtk-layer-shell = "0.8.0"
glib = "0.18.1"
tokio = { version = "1.32.0", features = ["rt", "time", "sync", "macros"] }
notify = { version = "6.1.1", features = ["fsevent-sys"] }
grass = {version = "0.13.1", default-features = false} #scss parsing
ron = "0.8.1"
serde = { version = "1.0.188", features = ["serde_derive"] }
colored="2.1.0"
env_logger = "0.10.1"
log = "0.4.20"

css-anim = {path = "../../css-anim", version = "*"}